import { create } from 'zustand';
import { IActivityWHStore } from './@type/useActivityWritingHubStore';

const useActivityWritingHubStore = create<IActivityWHStore>((set, get) => ({
    isNotFinishWriting: false,
    setIsNotFinishWriting: (flag:boolean) => {
        set(()=>({
            isNotFinishWriting: flag
        }))
    },
    sideNav: {
        titleList: [
            {
                title:'Spark Writing'
            },
            // {
            //     title: 'Free Writing'
            // },
        ],
    },
    loadDataHeadKor: {
        spark_writing: [
            {
                accessor: "year",
                header: "년도",
            },
            {
                accessor: "semester",
                header: "학기",
            },
            {
                accessor: "level",
                header: "Level",
            },
            {
                accessor: "book",
                header: "Book",
            },
            {
                accessor: "unit",
                header: 'unit'
            },{
                accessor: "topic",
                header: 'topic / outline format - text input'
            },{
                accessor: "outline_form",
                header: ''
            },{
                accessor: "outline_index",
                header: ''
            },{
                accessor: "outline_text",
                header: ''
            },{
                accessor: "outline_format_type",
                header: 'outline format type'
            },{
                accessor: "rubric_type",
                header: 'rubric type'
            },
        ],
    },
    loadData: {
        spark_writing: [
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "",
                "topic": "",
                "outline_form": "",
                "outline_index": "",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "1",
                "topic": "Descriptive Essays",
                "outline_form": "",
                "outline_index": "",
                "outline_text": "",
                "outline_format_type": "OL01",
                "rubric_type": "R01 Descriptive Essay",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "1",
                "topic": "Descriptive Essays",
                "outline_form": "title",
                "outline_index": "1",
                "outline_text": "Tet",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "1",
                "topic": "Descriptive Essays",
                "outline_form": "introduction",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "1",
                "topic": "Descriptive Essays",
                "outline_form": "body",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "1",
                "topic": "Descriptive Essays",
                "outline_form": "body",
                "outline_index": "2",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "1",
                "topic": "Descriptive Essays",
                "outline_form": "conclusion",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "2",
                "topic": "Informative Essays",
                "outline_form": "",
                "outline_index": "",
                "outline_text": "",
                "outline_format_type": "OL01",
                "rubric_type": "R02 Informative Essay",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "2",
                "topic": "Informative Essays",
                "outline_form": "title",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "2",
                "topic": "Informative Essays",
                "outline_form": "introduction",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "2",
                "topic": "Informative Essays",
                "outline_form": "body",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "2",
                "topic": "Informative Essays",
                "outline_form": "body",
                "outline_index": "2",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "2",
                "topic": "Informative Essays",
                "outline_form": "conclusion",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "3",
                "topic": "Personal Narratives",
                "outline_form": "",
                "outline_index": "",
                "outline_text": "",
                "outline_format_type": "OL02",
                "rubric_type": "R03 Personal Narrative",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "3",
                "topic": "Personal Narratives",
                "outline_form": "title",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "3",
                "topic": "Personal Narratives",
                "outline_form": "beginning",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "3",
                "topic": "Personal Narratives",
                "outline_form": "middle",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "3",
                "topic": "Personal Narratives",
                "outline_form": "middle",
                "outline_index": "2",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "3",
                "topic": "Personal Narratives",
                "outline_form": "middle",
                "outline_index": "3",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "3",
                "topic": "Personal Narratives",
                "outline_form": "end",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "4",
                "topic": "Realistic Function",
                "outline_form": "",
                "outline_index": "",
                "outline_text": "",
                "outline_format_type": "OL03",
                "rubric_type": "R04 Creative Writing",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "4",
                "topic": "Realistic Function",
                "outline_form": "title",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "4",
                "topic": "Realistic Function",
                "outline_form": "beginning",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "4",
                "topic": "Realistic Function",
                "outline_form": "beginning",
                "outline_index": "2",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "4",
                "topic": "Realistic Function",
                "outline_form": "middle",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "4",
                "topic": "Realistic Function",
                "outline_form": "middle",
                "outline_index": "2",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "4",
                "topic": "Realistic Function",
                "outline_form": "middle",
                "outline_index": "3",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "4",
                "topic": "Realistic Function",
                "outline_form": "end",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "5",
                "topic": "Persuasive Essays",
                "outline_form": "",
                "outline_index": "",
                "outline_text": "",
                "outline_format_type": "OL04",
                "rubric_type": "R05 Persuasive Essay",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "5",
                "topic": "Persuasive Essays",
                "outline_form": "title",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "5",
                "topic": "Persuasive Essays",
                "outline_form": "introduction",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "5",
                "topic": "Persuasive Essays",
                "outline_form": "body",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "5",
                "topic": "Persuasive Essays",
                "outline_form": "body",
                "outline_index": "2",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "5",
                "topic": "Persuasive Essays",
                "outline_form": "body",
                "outline_index": "3",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT4",
                "book": "Spark Writing 4-2",
                "unit": "5",
                "topic": "Persuasive Essays",
                "outline_form": "conclusion",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            // new
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "",
                "topic": "",
                "outline_form": "",
                "outline_index": "",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "1",
                "topic": "Descriptive Essays",
                "outline_form": "",
                "outline_index": "",
                "outline_text": "",
                "outline_format_type": "OL01",
                "rubric_type": "R01 Descriptive Essay",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "1",
                "topic": "Descriptive Essays",
                "outline_form": "title",
                "outline_index": "1",
                "outline_text": "Tet",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "1",
                "topic": "Descriptive Essays",
                "outline_form": "introduction",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "1",
                "topic": "Descriptive Essays",
                "outline_form": "body",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "1",
                "topic": "Descriptive Essays",
                "outline_form": "body",
                "outline_index": "2",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "1",
                "topic": "Descriptive Essays",
                "outline_form": "conclusion",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "2",
                "topic": "Informative Essays",
                "outline_form": "",
                "outline_index": "",
                "outline_text": "",
                "outline_format_type": "OL01",
                "rubric_type": "R02 Informative Essay",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "2",
                "topic": "Informative Essays",
                "outline_form": "title",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "2",
                "topic": "Informative Essays",
                "outline_form": "introduction",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "2",
                "topic": "Informative Essays",
                "outline_form": "body",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "2",
                "topic": "Informative Essays",
                "outline_form": "body",
                "outline_index": "2",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "2",
                "topic": "Informative Essays",
                "outline_form": "conclusion",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "3",
                "topic": "Personal Narratives",
                "outline_form": "",
                "outline_index": "",
                "outline_text": "",
                "outline_format_type": "OL02",
                "rubric_type": "R03 Personal Narrative",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "3",
                "topic": "Personal Narratives",
                "outline_form": "title",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "3",
                "topic": "Personal Narratives",
                "outline_form": "beginning",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "3",
                "topic": "Personal Narratives",
                "outline_form": "middle",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "3",
                "topic": "Personal Narratives",
                "outline_form": "middle",
                "outline_index": "2",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "3",
                "topic": "Personal Narratives",
                "outline_form": "middle",
                "outline_index": "3",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "3",
                "topic": "Personal Narratives",
                "outline_form": "end",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "4",
                "topic": "Realistic Function",
                "outline_form": "",
                "outline_index": "",
                "outline_text": "",
                "outline_format_type": "OL03",
                "rubric_type": "R04 Creative Writing",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "4",
                "topic": "Realistic Function",
                "outline_form": "title",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "4",
                "topic": "Realistic Function",
                "outline_form": "beginning",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "4",
                "topic": "Realistic Function",
                "outline_form": "beginning",
                "outline_index": "2",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "4",
                "topic": "Realistic Function",
                "outline_form": "middle",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "4",
                "topic": "Realistic Function",
                "outline_form": "middle",
                "outline_index": "2",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "4",
                "topic": "Realistic Function",
                "outline_form": "middle",
                "outline_index": "3",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "4",
                "topic": "Realistic Function",
                "outline_form": "end",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "5",
                "topic": "Persuasive Essays",
                "outline_form": "",
                "outline_index": "",
                "outline_text": "",
                "outline_format_type": "OL04",
                "rubric_type": "R05 Persuasive Essay",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "5",
                "topic": "Persuasive Essays",
                "outline_form": "title",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "5",
                "topic": "Persuasive Essays",
                "outline_form": "introduction",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "5",
                "topic": "Persuasive Essays",
                "outline_form": "body",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "5",
                "topic": "Persuasive Essays",
                "outline_form": "body",
                "outline_index": "2",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "5",
                "topic": "Persuasive Essays",
                "outline_form": "body",
                "outline_index": "3",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
            {
                "year": "2020",
                "semester": "2",
                "level": "GT3",
                "book": "Spark Writing B-2",
                "unit": "5",
                "topic": "Persuasive Essays",
                "outline_form": "conclusion",
                "outline_index": "1",
                "outline_text": "",
                "outline_format_type": "",
                "rubric_type": "",
            },
        ],
    },

    loadDataUpdateFlag : 0,
    loadDataUpdateFlagInit: () => {
        set(()=>({loadDataUpdateFlag:0}))
    },
    setLoadDataSparkWritingInput: (text:string, rowIndex: number) => {
        let dumpSparkWritingData = get().loadData.spark_writing;
        dumpSparkWritingData[rowIndex].outline_text = text;
        set(()=>({
            loadDataUpdateFlag: 1,
            loadData: {
                spark_writing: dumpSparkWritingData,
            }
        }))
    },
    openControlBox: false,
    setOpenControlBox: (flag:boolean) => {
        set(()=>({
            openControlBox: flag
        }))
    }
}));

export default useActivityWritingHubStore;