const GRAMMAR_CHECK:string = process.env.REACT_APP_GRAMMAR_CREATE_ORIGIN_CHANGE_TEXTS?process.env.REACT_APP_GRAMMAR_CREATE_ORIGIN_CHANGE_TEXTS:'';
const GRAMMAR_COMPARE:string = process.env.REACT_APP_GRAMMAR_COMPARE_TEXTS?process.env.REACT_APP_GRAMMAR_COMPARE_TEXTS:'';
const CHATBOT_API_URL:string = process.env.REACT_APP_CHATBOT_API_URL?process.env.REACT_APP_CHATBOT_API_URL:'';
const LEVEL_AND_TEXTBOOK_SPEAKING:string = process.env.REACT_APP_LEVEL_AND_TEXTBOOK_SPEAKING?process.env.REACT_APP_LEVEL_AND_TEXTBOOK_SPEAKING:'';
const LEVEL_AND_TEXTBOOK_WRITING:string = process.env.REACT_APP_LEVEL_AND_TEXTBOOK_WRITING?process.env.REACT_APP_LEVEL_AND_TEXTBOOK_WRITING:'';

export const CONFIG = {
    GRAMMAR: {
        CHECK:GRAMMAR_CHECK,
        COMPARE:GRAMMAR_COMPARE
    },
    CHATBOT: {
        URL:CHATBOT_API_URL
    },
    LEVEL_AND_TEXTBOOK: {
        SPEAKING:LEVEL_AND_TEXTBOOK_SPEAKING,
        WRITING:LEVEL_AND_TEXTBOOK_WRITING
    }
}